"""Create Amazon Report Table

Revision ID: 0002
Revises: 0001
Create Date: 2023-07-06 12:32:14.720561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_report',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('seller_partner_id', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('status_updated_at', sa.BigInteger(), nullable=True),
    sa.Column('request_start_time', sa.DateTime(), nullable=True),
    sa.Column('request_end_time', sa.DateTime(), nullable=True),
    sa.Column('document_id', sa.String(length=255), nullable=True),
    sa.Column('document_id_updated_at', sa.BigInteger(), nullable=True),
    sa.Column('queue_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deactivated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_report')
    # ### end Alembic commands ###
