"""Create Amazon Item Master Table

Revision ID: 0003
Revises: 0002
Create Date: 2023-07-06 12:32:54.530072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_item_master',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('selling_partner_id', sa.String(length=255), nullable=True),
    sa.Column('item_name', sa.String(length=250), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('listing_id', sa.String(length=100), nullable=False),
    sa.Column('seller_sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('asin', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('fulfillment_channel', sa.Enum('AMAZON_IN', 'DEFAULT', name='fulfillmentchannel'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'INCOMPLETE', name='itemmasterstatus'), nullable=True),
    sa.Column('max_retail_price', sa.Numeric(), nullable=False),
    sa.Column('brand', sa.String(length=250), nullable=True),
    sa.Column('brand_updated_at', sa.BigInteger(), nullable=True),
    sa.Column('cogs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cogs_updated_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_sku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_item_master')
    # ### end Alembic commands ###
