"""Create Amazon Order Report Table

Revision ID: 0004
Revises: 0003
Create Date: 2023-07-06 12:33:29.966208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_order_report',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('selling_partner_id', sa.String(length=255), nullable=True),
    sa.Column('amazon_order_id', sa.String(length=255), nullable=True),
    sa.Column('merchant_order_id', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('last_updated_date', sa.Date(), nullable=True),
    sa.Column('order_status', sa.String(length=255), nullable=True),
    sa.Column('fulfillment_channel', sa.String(length=255), nullable=True),
    sa.Column('sales_channel', sa.String(length=255), nullable=True),
    sa.Column('ship_service_level', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('asin', sa.String(length=255), nullable=True),
    sa.Column('item_status', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('item_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('item_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gift_wrap_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gift_wrap_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('item_promotion_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ship_promotion_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ship_city', sa.String(length=255), nullable=True),
    sa.Column('ship_state', sa.String(length=255), nullable=True),
    sa.Column('ship_postal_code', sa.String(length=255), nullable=True),
    sa.Column('ship_country', sa.String(length=255), nullable=True),
    sa.Column('gross_sales', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_order_report')
    # ### end Alembic commands ###
