"""Create Amazon Sales Traffic Asin Table

Revision ID: 0006
Revises: 0005
Create Date: 2023-07-06 12:34:30.156863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_sales_traffic_asin',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('selling_partner_id', sa.String(length=255), nullable=True),
    sa.Column('parent_asin', sa.String(length=255), nullable=True),
    sa.Column('child_asin', sa.String(length=255), nullable=True),
    sa.Column('units_ordered', sa.Integer(), nullable=True),
    sa.Column('ordered_product_sales_amount', sa.Numeric(), nullable=True),
    sa.Column('ordered_product_sales_currency_code', sa.String(length=50), nullable=True),
    sa.Column('total_order_items', sa.Integer(), nullable=True),
    sa.Column('browser_sessions', sa.Integer(), nullable=True),
    sa.Column('mobile_app_sessions', sa.Integer(), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('browser_session_percentage', sa.Numeric(), nullable=True),
    sa.Column('mobile_app_session_percentage', sa.Numeric(), nullable=True),
    sa.Column('session_percentage', sa.Numeric(), nullable=True),
    sa.Column('browser_page_views', sa.Integer(), nullable=True),
    sa.Column('mobile_app_page_views', sa.Integer(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=True),
    sa.Column('browser_page_views_percentage', sa.Numeric(), nullable=True),
    sa.Column('mobile_app_page_views_percentage', sa.Numeric(), nullable=True),
    sa.Column('page_views_percentage', sa.Numeric(), nullable=True),
    sa.Column('buy_box_percentage', sa.Numeric(), nullable=True),
    sa.Column('unit_session_percentage', sa.Numeric(), nullable=True),
    sa.Column('asin_granularity', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_sales_traffic_asin')
    # ### end Alembic commands ###
