"""Create Amazon Sales Traffic Summary Table

Revision ID: 0007
Revises: 0006
Create Date: 2023-07-06 12:35:26.107546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_sales_traffic_summary',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('selling_partner_id', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ordered_product_sales_amount', sa.Numeric(), nullable=True),
    sa.Column('ordered_product_sales_currency_code', sa.String(length=50), nullable=True),
    sa.Column('units_ordered', sa.Integer(), nullable=True),
    sa.Column('total_order_items', sa.Integer(), nullable=True),
    sa.Column('average_sales_per_order_item_amount', sa.Numeric(), nullable=True),
    sa.Column('average_sales_per_order_item_currency_code', sa.String(length=50), nullable=True),
    sa.Column('average_units_per_order_item', sa.Numeric(), nullable=True),
    sa.Column('average_selling_price_amount', sa.Numeric(), nullable=True),
    sa.Column('average_selling_price_currency_code', sa.String(length=50), nullable=True),
    sa.Column('units_refunded', sa.Integer(), nullable=True),
    sa.Column('refund_rate', sa.Numeric(), nullable=True),
    sa.Column('claims_granted', sa.Integer(), nullable=True),
    sa.Column('claims_amount_amount', sa.Numeric(), nullable=True),
    sa.Column('claims_amount_currency_code', sa.String(length=50), nullable=True),
    sa.Column('shipped_product_sales_amount', sa.Numeric(), nullable=True),
    sa.Column('shipped_product_sales_currency_code', sa.String(length=50), nullable=True),
    sa.Column('units_shipped', sa.Integer(), nullable=True),
    sa.Column('orders_shipped', sa.Integer(), nullable=True),
    sa.Column('browser_page_views', sa.BigInteger(), nullable=True),
    sa.Column('mobile_app_page_views', sa.BigInteger(), nullable=True),
    sa.Column('page_views', sa.BigInteger(), nullable=True),
    sa.Column('browser_sessions', sa.BigInteger(), nullable=True),
    sa.Column('mobile_app_sessions', sa.BigInteger(), nullable=True),
    sa.Column('sessions', sa.BigInteger(), nullable=True),
    sa.Column('buy_box_percentage', sa.Numeric(), nullable=True),
    sa.Column('order_item_session_percentage', sa.Numeric(), nullable=True),
    sa.Column('unit_session_percentage', sa.Numeric(), nullable=True),
    sa.Column('average_offer_count', sa.Integer(), nullable=True),
    sa.Column('average_parent_items', sa.Integer(), nullable=True),
    sa.Column('feedback_received', sa.Integer(), nullable=True),
    sa.Column('negative_feedback_received', sa.Integer(), nullable=True),
    sa.Column('received_negative_feedback_rate', sa.Numeric(), nullable=True),
    sa.Column('date_granularity', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_sales_traffic_summary')
    # ### end Alembic commands ###
