"""Create Amazon Returns Table

Revision ID: 0008
Revises: 0007
Create Date: 2023-07-06 12:35:54.689778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selling_partner_id', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('return_request_date', sa.Date(), nullable=True),
    sa.Column('return_request_status', sa.String(length=255), nullable=True),
    sa.Column('amazon_rma_id', sa.String(length=255), nullable=True),
    sa.Column('merchant_rma_id', sa.String(length=255), nullable=True),
    sa.Column('label_type', sa.String(length=255), nullable=True),
    sa.Column('label_cost', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('return_carrier', sa.String(length=255), nullable=True),
    sa.Column('tracking_id', sa.String(length=255), nullable=True),
    sa.Column('label_to_be_paid_by', sa.String(length=255), nullable=True),
    sa.Column('a_to_z_claim', sa.Boolean(), nullable=True),
    sa.Column('is_prime', sa.Boolean(), nullable=True),
    sa.Column('asin', sa.String(length=10), nullable=True),
    sa.Column('merchant_sku', sa.String(length=255), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('return_quantity', sa.Integer(), nullable=True),
    sa.Column('return_reason', sa.String(length=255), nullable=True),
    sa.Column('in_policy', sa.Boolean(), nullable=True),
    sa.Column('return_type', sa.String(length=255), nullable=True),
    sa.Column('resolution', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('return_delivery_date', sa.Date(), nullable=True),
    sa.Column('order_amount', sa.Float(), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('safet_action_reason', sa.String(length=255), nullable=True),
    sa.Column('safet_claim_id', sa.String(length=255), nullable=True),
    sa.Column('safet_claim_state', sa.String(length=255), nullable=True),
    sa.Column('safet_claim_creation_time', sa.DateTime(), nullable=True),
    sa.Column('safet_claim_reimbursement_amount', sa.Float(), nullable=True),
    sa.Column('refunded_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_return')
    # ### end Alembic commands ###
