"""Create Amazon Settlement Report Table

Revision ID: 0009
Revises: 0008
Create Date: 2023-07-06 12:36:17.073728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_settlement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('selling_partner_id', sa.String(length=255), nullable=True),
    sa.Column('settlement_id', sa.BigInteger(), nullable=False),
    sa.Column('settlement_start_date', sa.DateTime(), nullable=True),
    sa.Column('settlement_end_date', sa.DateTime(), nullable=True),
    sa.Column('deposit_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('transaction_type', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('merchant_order_id', sa.String(length=255), nullable=True),
    sa.Column('adjustment_id', sa.String(length=255), nullable=True),
    sa.Column('shipment_id', sa.String(length=255), nullable=True),
    sa.Column('marketplace_name', sa.String(length=255), nullable=True),
    sa.Column('shipment_fee_type', sa.String(length=255), nullable=True),
    sa.Column('shipment_fee_amount', sa.Numeric(), nullable=True),
    sa.Column('order_fee_type', sa.String(length=255), nullable=True),
    sa.Column('order_fee_amount', sa.Numeric(), nullable=True),
    sa.Column('fulfillment_id', sa.String(length=255), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('order_item_code', sa.String(length=255), nullable=True),
    sa.Column('merchant_order_item_id', sa.String(length=255), nullable=True),
    sa.Column('merchant_adjustment_item_id', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('quantity_purchased', sa.Integer(), nullable=True),
    sa.Column('price_type', sa.String(length=255), nullable=True),
    sa.Column('price_amount', sa.Numeric(), nullable=True),
    sa.Column('item_related_fee_type', sa.String(length=255), nullable=True),
    sa.Column('item_related_fee_amount', sa.Numeric(), nullable=True),
    sa.Column('misc_fee_amount', sa.Numeric(), nullable=True),
    sa.Column('other_fee_amount', sa.Numeric(), nullable=True),
    sa.Column('other_fee_reason_description', sa.Text(), nullable=True),
    sa.Column('promotion_id', sa.String(length=255), nullable=True),
    sa.Column('promotion_type', sa.String(length=255), nullable=True),
    sa.Column('promotion_amount', sa.Numeric(), nullable=True),
    sa.Column('direct_payment_type', sa.String(length=255), nullable=True),
    sa.Column('direct_payment_amount', sa.Numeric(), nullable=True),
    sa.Column('other_amount', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_settlement')
    # ### end Alembic commands ###
