"""Create Amazon Ledger Summary Table

Revision ID: 0010
Revises: 0009
Create Date: 2023-07-06 12:36:41.299660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_ledger_summary',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('selling_partner_id', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('fnsku', sa.String(length=100), nullable=False),
    sa.Column('asin', sa.String(length=100), nullable=False),
    sa.Column('msku', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('disposition', sa.String(length=100), nullable=False),
    sa.Column('starting_warehouse_balance', sa.Integer(), nullable=False),
    sa.Column('in_transit_btw_warehouse', sa.Integer(), nullable=False),
    sa.Column('receipts', sa.Integer(), nullable=False),
    sa.Column('customer_shipments', sa.Integer(), nullable=False),
    sa.Column('customer_returns', sa.Integer(), nullable=False),
    sa.Column('vendor_returns', sa.Integer(), nullable=False),
    sa.Column('warehouse_transfer', sa.Integer(), nullable=False),
    sa.Column('found', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('damaged', sa.Integer(), nullable=False),
    sa.Column('disposed', sa.Integer(), nullable=False),
    sa.Column('other_events', sa.Integer(), nullable=False),
    sa.Column('ending_warehouse_balance', sa.Integer(), nullable=False),
    sa.Column('unknown_events', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_ledger_summary')
    # ### end Alembic commands ###
