"""Create Amazon Stock Transfer Adhoc Table

Revision ID: 0011
Revises: 0010
Create Date: 2023-07-06 12:37:53.936641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_stock_transfer_adhoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selling_partner_id', sa.String(length=255), nullable=True),
    sa.Column('gstin_of_receiver', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('ship_from_fc', sa.String(length=255), nullable=True),
    sa.Column('ship_from_city', sa.String(length=255), nullable=True),
    sa.Column('ship_from_state', sa.String(length=255), nullable=True),
    sa.Column('ship_from_country', sa.String(length=255), nullable=True),
    sa.Column('ship_from_postal_code', sa.String(length=255), nullable=True),
    sa.Column('ship_to_fc', sa.String(length=255), nullable=True),
    sa.Column('ship_to_city', sa.String(length=255), nullable=True),
    sa.Column('ship_to_state', sa.String(length=255), nullable=True),
    sa.Column('ship_to_country', sa.String(length=255), nullable=True),
    sa.Column('ship_to_postal_code', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('invoice_value', sa.Float(), nullable=True),
    sa.Column('asin', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('hsn_code', sa.String(length=255), nullable=True),
    sa.Column('taxable_value', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_rate', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('utgst_rate', sa.Float(), nullable=True),
    sa.Column('utgst_amount', sa.Float(), nullable=True),
    sa.Column('cgst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('compensatory_cess_rate', sa.Float(), nullable=True),
    sa.Column('compensatory_cess_amount', sa.Float(), nullable=True),
    sa.Column('gstin_of_supplier', sa.String(length=255), nullable=True),
    sa.Column('irn_number', sa.String(length=255), nullable=True),
    sa.Column('irn_filing_status', sa.String(length=255), nullable=True),
    sa.Column('irn_date', sa.Date(), nullable=True),
    sa.Column('irn_error_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_stock_transfer_adhoc')
    # ### end Alembic commands ###
