"""Create Amazon Order Table

Revision ID: 0012
Revises: 0011
Create Date: 2023-07-06 12:38:19.338174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_order',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('selling_partner_id', sa.String(length=255), nullable=True),
    sa.Column('buyer_email', sa.String(length=255), nullable=True),
    sa.Column('amazon_order_id', sa.String(length=255), nullable=True),
    sa.Column('earliest_ship_date', sa.DateTime(), nullable=True),
    sa.Column('sales_channel', sa.String(), nullable=True),
    sa.Column('order_status', sa.String(length=255), nullable=True),
    sa.Column('number_of_items_shipped', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=255), nullable=True),
    sa.Column('is_premium_order', sa.Boolean(), nullable=True),
    sa.Column('is_prime', sa.Boolean(), nullable=True),
    sa.Column('fulfillment_channel', sa.String(length=255), nullable=True),
    sa.Column('number_of_items_unshipped', sa.Integer(), nullable=True),
    sa.Column('has_regulated_items', sa.Boolean(), nullable=True),
    sa.Column('is_replacement_order', sa.Boolean(), nullable=True),
    sa.Column('is_sold_by_ab', sa.Boolean(), nullable=True),
    sa.Column('latest_ship_date', sa.DateTime(), nullable=True),
    sa.Column('ship_service_level', sa.String(length=255), nullable=True),
    sa.Column('is_ispu', sa.Boolean(), nullable=True),
    sa.Column('marketplace_id', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('shipping_address_state_or_region', sa.String(length=255), nullable=True),
    sa.Column('shipping_address_postal_code', sa.Integer(), nullable=True),
    sa.Column('shipping_address_city', sa.String(length=255), nullable=True),
    sa.Column('shipping_address_country_code', sa.String(length=20), nullable=True),
    sa.Column('is_access_point_order', sa.Boolean(), nullable=True),
    sa.Column('seller_order_id', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=255), nullable=True),
    sa.Column('is_business_order', sa.Boolean(), nullable=True),
    sa.Column('order_total_currency_code', sa.String(length=20), nullable=True),
    sa.Column('order_total_amount', sa.Numeric(), nullable=True),
    sa.Column('payment_method_details', sa.String(length=100), nullable=True),
    sa.Column('is_global_express_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), nullable=True),
    sa.Column('shipment_service_level_category', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_order')
    # ### end Alembic commands ###
