"""Create Amazon Fba Return Table

Revision ID: 0014
Revises: 0013
Create Date: 2023-07-06 12:39:05.619347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0014'
down_revision = '0013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_fba_return',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('selling_partner_id', sa.String(length=255), nullable=True),
    sa.Column('return_date', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('asin', sa.String(length=255), nullable=True),
    sa.Column('fnsku', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('fulfillment_center_id', sa.String(length=255), nullable=True),
    sa.Column('detailed_disposition', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('license_plate_number', sa.String(length=255), nullable=True),
    sa.Column('customer_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_fba_return')
    # ### end Alembic commands ###
