"""Create Amazon Fba Replacement Table

Revision ID: 0015
Revises: 0014
Create Date: 2023-07-06 12:39:21.992245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0015'
down_revision = '0014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_fba_replacement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('selling_partner_id', sa.String(length=255), nullable=True),
    sa.Column('shipment_date', sa.BigInteger(), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('asin', sa.String(length=255), nullable=True),
    sa.Column('fulfillment_center_id', sa.String(length=255), nullable=True),
    sa.Column('original_fulfillment_center_id', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('replacement_reason_code', sa.String(length=255), nullable=True),
    sa.Column('replacement_amazon_order_id', sa.String(length=255), nullable=True),
    sa.Column('original_amazon_order_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_fba_replacement')
    # ### end Alembic commands ###
