"""Create Amazon Ad's Tables

Revision ID: 0016
Revises: 0015
Create Date: 2023-07-12 14:57:06.667802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0016'
down_revision = '0015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_sponsored_brand',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('campaign_budget_currency_code', sa.String(length=255), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('ad_group_name', sa.String(length=255), nullable=True),
    sa.Column('attribution_type', sa.String(length=255), nullable=True),
    sa.Column('purchased_asin', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_category', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('az_sponsored_display',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_group_name', sa.String(length=255), nullable=True),
    sa.Column('ad_id', sa.BigInteger(), nullable=True),
    sa.Column('asin', sa.String(length=255), nullable=True),
    sa.Column('attributed_conversions_7d', sa.Integer(), nullable=True),
    sa.Column('attributed_conversions_7d_same_sku', sa.Integer(), nullable=True),
    sa.Column('attributed_sales_7d', sa.Integer(), nullable=True),
    sa.Column('attributed_sales_7d_same_sku', sa.Integer(), nullable=True),
    sa.Column('attributed_units_ordered_7d', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('view_impressions', sa.Integer(), nullable=True),
    sa.Column('video_complete_views', sa.Integer(), nullable=True),
    sa.Column('video_first_quartile_views', sa.Integer(), nullable=True),
    sa.Column('video_midpoint_views', sa.Integer(), nullable=True),
    sa.Column('video_third_quartile_views', sa.Integer(), nullable=True),
    sa.Column('video_unmutes', sa.Integer(), nullable=True),
    sa.Column('vtr', sa.Integer(), nullable=True),
    sa.Column('vctr', sa.Integer(), nullable=True),
    sa.Column('avg_impressions_frequency', sa.Numeric(), nullable=True),
    sa.Column('cumulative_reach', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('az_sponsored_product',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_group_name', sa.String(length=255), nullable=True),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_id', sa.BigInteger(), nullable=True),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost_per_click', sa.Numeric(), nullable=True),
    sa.Column('click_through_rate', sa.Numeric(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('spend', sa.Numeric(), nullable=True),
    sa.Column('campaign_budget_currency_code', sa.String(), nullable=True),
    sa.Column('campaign_budget_amount', sa.Numeric(), nullable=True),
    sa.Column('campaign_budget_type', sa.String(), nullable=True),
    sa.Column('campaign_status', sa.String(), nullable=True),
    sa.Column('advertised_asin', sa.String(), nullable=True),
    sa.Column('advertised_sku', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('az_order_report', 'gross_sales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_order_report', sa.Column('gross_sales', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_table('az_sponsored_product')
    op.drop_table('az_sponsored_display')
    op.drop_table('az_sponsored_brand')
    # ### end Alembic commands ###
