"""Create Amazon Financial Events Table

Revision ID: 0017
Revises: 0016
Create Date: 2023-07-17 22:39:47.547212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0017'
down_revision = '0016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_financial_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('asp_id', sa.String(length=255), nullable=True),
    sa.Column('az_order_id', sa.String(length=255), nullable=True),
    sa.Column('seller_order_id', sa.String(length=255), nullable=True),
    sa.Column('market_place', sa.String(length=255), nullable=True),
    sa.Column('posted_date', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=255), nullable=True),
    sa.Column('event_json', sa.JSON(), nullable=True),
    sa.Column('finance_type', sa.String(length=255), nullable=True),
    sa.Column('finance_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deactivated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_financial_event')
    # ### end Alembic commands ###
