"""Create Product performance Table

Revision ID: 0018
Revises: 0017
Create Date: 2023-07-20 19:37:56.318976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0018'
down_revision = '0017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_product_performance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('asp_id', sa.String(length=255), nullable=True),
    sa.Column('az_order_id', sa.String(length=255), nullable=True),
    sa.Column('seller_order_id', sa.String(length=255), nullable=True),
    sa.Column('seller_sku', sa.String(length=255), nullable=True),
    sa.Column('expenses', sa.Numeric(), nullable=True),
    sa.Column('gross_sales', sa.Numeric(), nullable=True),
    sa.Column('units_sold', sa.BigInteger(), nullable=True),
    sa.Column('units_returned', sa.BigInteger(), nullable=True),
    sa.Column('market_place_fee', sa.Numeric(), nullable=True),
    sa.Column('forward_fba_fee', sa.Numeric(), nullable=True),
    sa.Column('reverse_fba_fee', sa.Numeric(), nullable=True),
    sa.Column('returns', sa.Numeric(), nullable=True),
    sa.Column('shipment_date', sa.String(length=255), nullable=True),
    sa.Column('refund_date', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deactivated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_product_performance')
    # ### end Alembic commands ###
