"""Update Item Master Table

Revision ID: 0021
Revises: 0020
Create Date: 2023-08-01 17:20:34.745492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0021'
down_revision = '0020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_item_master', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_item_master', sa.Column('subcategory', sa.String(length=250), nullable=True))
    op.add_column('az_item_master', sa.Column('category_rank', sa.BigInteger(), nullable=True))
    op.add_column('az_item_master', sa.Column('subcategory_rank', sa.BigInteger(), nullable=True))
    op.add_column('az_item_master', sa.Column('face_image', sa.Text(), nullable=True))
    op.add_column('az_item_master', sa.Column('other_images', sa.JSON(), nullable=True))
    op.drop_column('az_ledger_summary', 'selling_partner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_ledger_summary', sa.Column('selling_partner_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('az_item_master', 'other_images')
    op.drop_column('az_item_master', 'face_image')
    op.drop_column('az_item_master', 'subcategory_rank')
    op.drop_column('az_item_master', 'category_rank')
    op.drop_column('az_item_master', 'subcategory')
    op.drop_column('az_item_master', 'category')
    # ### end Alembic commands ###
