"""update_amazon_sales_traffic_summary

Revision ID: 0024
Revises: 0023
Create Date: 2023-08-13 21:41:35.968726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0024'
down_revision = '0023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_sales_traffic_asin', sa.Column('payload_date', sa.Date(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('ordered_product_sales_amount_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('ordered_product_sales_currency_code_b2b', sa.String(length=50), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('units_ordered_b2b', sa.Integer(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('total_order_items_b2b', sa.Integer(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('average_sales_per_order_item_amount_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('average_sales_per_order_item_currency_code_b2b', sa.String(length=50), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('average_units_per_order_item_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('average_selling_price_amount_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('average_selling_price_currency_code_b2b', sa.String(length=50), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('browser_page_views_b2b', sa.BigInteger(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('mobile_app_page_views_b2b', sa.BigInteger(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('page_views_b2b', sa.BigInteger(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('browser_sessions_b2b', sa.BigInteger(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('mobile_app_sessions_b2b', sa.BigInteger(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('sessions_b2b', sa.BigInteger(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('buy_box_percentage_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('order_item_session_percentage_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('unit_session_percentage_b2b', sa.Numeric(), nullable=True))
    op.drop_column('az_sales_traffic_summary', 'selling_partner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_sales_traffic_summary', sa.Column('selling_partner_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('az_sales_traffic_summary', 'unit_session_percentage_b2b')
    op.drop_column('az_sales_traffic_summary', 'order_item_session_percentage_b2b')
    op.drop_column('az_sales_traffic_summary', 'buy_box_percentage_b2b')
    op.drop_column('az_sales_traffic_summary', 'sessions_b2b')
    op.drop_column('az_sales_traffic_summary', 'mobile_app_sessions_b2b')
    op.drop_column('az_sales_traffic_summary', 'browser_sessions_b2b')
    op.drop_column('az_sales_traffic_summary', 'page_views_b2b')
    op.drop_column('az_sales_traffic_summary', 'mobile_app_page_views_b2b')
    op.drop_column('az_sales_traffic_summary', 'browser_page_views_b2b')
    op.drop_column('az_sales_traffic_summary', 'average_selling_price_currency_code_b2b')
    op.drop_column('az_sales_traffic_summary', 'average_selling_price_amount_b2b')
    op.drop_column('az_sales_traffic_summary', 'average_units_per_order_item_b2b')
    op.drop_column('az_sales_traffic_summary', 'average_sales_per_order_item_currency_code_b2b')
    op.drop_column('az_sales_traffic_summary', 'average_sales_per_order_item_amount_b2b')
    op.drop_column('az_sales_traffic_summary', 'total_order_items_b2b')
    op.drop_column('az_sales_traffic_summary', 'units_ordered_b2b')
    op.drop_column('az_sales_traffic_summary', 'ordered_product_sales_currency_code_b2b')
    op.drop_column('az_sales_traffic_summary', 'ordered_product_sales_amount_b2b')
    op.drop_column('az_sales_traffic_asin', 'payload_date')
    # ### end Alembic commands ###
