"""update amazon_sales_traffic_asin

Revision ID: 0025
Revises: 0024
Create Date: 2023-08-13 22:48:21.710651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0025'
down_revision = '0024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_sales_traffic_asin', sa.Column('units_ordered_b2b', sa.Integer(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('ordered_product_sales_amount_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('ordered_product_sales_currency_code_b2b', sa.String(length=50), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('total_order_items_b2b', sa.Integer(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('browser_sessions_b2b', sa.Integer(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('mobile_app_sessions_b2b', sa.Integer(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('sessions_b2b', sa.Integer(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('browser_session_percentage_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('mobile_app_session_percentage_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('session_percentage_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('browser_page_views_b2b', sa.Integer(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('mobile_app_page_views_b2b', sa.Integer(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('page_views_b2b', sa.Integer(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('browser_page_views_percentage_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('mobile_app_page_views_percentage_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('page_views_percentage_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('buy_box_percentage_b2b', sa.Numeric(), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('unit_session_percentage_b2b', sa.Numeric(), nullable=True))
    op.drop_column('az_sales_traffic_asin', 'selling_partner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_sales_traffic_asin', sa.Column('selling_partner_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('az_sales_traffic_asin', 'unit_session_percentage_b2b')
    op.drop_column('az_sales_traffic_asin', 'buy_box_percentage_b2b')
    op.drop_column('az_sales_traffic_asin', 'page_views_percentage_b2b')
    op.drop_column('az_sales_traffic_asin', 'mobile_app_page_views_percentage_b2b')
    op.drop_column('az_sales_traffic_asin', 'browser_page_views_percentage_b2b')
    op.drop_column('az_sales_traffic_asin', 'page_views_b2b')
    op.drop_column('az_sales_traffic_asin', 'mobile_app_page_views_b2b')
    op.drop_column('az_sales_traffic_asin', 'browser_page_views_b2b')
    op.drop_column('az_sales_traffic_asin', 'session_percentage_b2b')
    op.drop_column('az_sales_traffic_asin', 'mobile_app_session_percentage_b2b')
    op.drop_column('az_sales_traffic_asin', 'browser_session_percentage_b2b')
    op.drop_column('az_sales_traffic_asin', 'sessions_b2b')
    op.drop_column('az_sales_traffic_asin', 'mobile_app_sessions_b2b')
    op.drop_column('az_sales_traffic_asin', 'browser_sessions_b2b')
    op.drop_column('az_sales_traffic_asin', 'total_order_items_b2b')
    op.drop_column('az_sales_traffic_asin', 'ordered_product_sales_currency_code_b2b')
    op.drop_column('az_sales_traffic_asin', 'ordered_product_sales_amount_b2b')
    op.drop_column('az_sales_traffic_asin', 'units_ordered_b2b')
    # ### end Alembic commands ###
