"""Create Amazon Fba Reimbursements Table

Revision ID: 0026
Revises: 0025
Create Date: 2023-08-31 18:19:34.278588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0026'
down_revision = '0025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_fba_reimbursements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('asp_id', sa.String(length=255), nullable=True),
    sa.Column('approval_date', sa.String(length=255), nullable=True),
    sa.Column('reimbursement_id', sa.BigInteger(), nullable=True),
    sa.Column('case_id', sa.String(length=255), nullable=True),
    sa.Column('az_order_id', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('fnsku', sa.String(length=255), nullable=True),
    sa.Column('asin', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('currency_unit', sa.String(length=255), nullable=True),
    sa.Column('amount_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity_reimbursed_cash', sa.BigInteger(), nullable=True),
    sa.Column('quantity_reimbursed_inventory', sa.BigInteger(), nullable=True),
    sa.Column('quantity_reimbursed_total', sa.BigInteger(), nullable=True),
    sa.Column('original_reimbursement_id', sa.BigInteger(), nullable=True),
    sa.Column('original_reimbursement_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('az_fba_returns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('asp_id', sa.String(length=255), nullable=True),
    sa.Column('return_date', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('asin', sa.String(length=255), nullable=True),
    sa.Column('fnsku', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('fulfillment_center_id', sa.String(length=255), nullable=True),
    sa.Column('detailed_disposition', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('license_plate_number', sa.String(length=255), nullable=True),
    sa.Column('customer_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('az_fba_return')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_fba_return',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('selling_partner_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('return_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('asin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fnsku', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fulfillment_center_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('detailed_disposition', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('license_plate_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('asp_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='az_fba_return_pkey'),
    sa.UniqueConstraint('order_id', name='az_fba_return_order_id_key')
    )
    op.drop_table('az_fba_returns')
    op.drop_table('az_fba_reimbursements')
    # ### end Alembic commands ###
