"""Create Amazon Fba Customer Shipment Sales Table

Revision ID: 0027
Revises: 0026
Create Date: 2023-09-06 19:58:29.908656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0027'
down_revision = '0026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_fba_customer_shipment_sales',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('asp_id', sa.String(length=255), nullable=True),
    sa.Column('shipment_date', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('fnsku', sa.String(length=255), nullable=True),
    sa.Column('asin', sa.String(length=255), nullable=True),
    sa.Column('fulfillment_center_id', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('amazon_order_id', sa.String(length=255), nullable=True),
    sa.Column('item_price_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gift_wrap_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ship_city', sa.String(length=255), nullable=True),
    sa.Column('ship_state', sa.String(length=255), nullable=True),
    sa.Column('ship_postal_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_fba_customer_shipment_sales')
    # ### end Alembic commands ###
