"""Pincode Seeder

Revision ID: 0028
Revises: 0027
Create Date: 2023-09-12 19:58:29.908656

"""
import json

from alembic import op
from app import base_dir
from app.models.postal_code_master import PostalCodeMaster


# revision identifiers, used by Alembic.
revision = '0028'
down_revision = '0027'
branch_labels = None
depends_on = None


def upgrade():
    # Call the seeder to store postal code master data
    seed()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def seed():
    # ### commands auto generated by Alembic - please adjust! ###
    file = open(file=base_dir + '/app/static/files/postal_code_sep_12.json', mode='r')
    data = json.loads(file.read())

    # Create a set to store the pin codes that are already inserted
    existing_pin_codes = set()

    # Get existing pin codes from the database
    existing_pin_codes_query = PostalCodeMaster.get_all_pincode()
    existing_pin_codes.update(str(row.pincode) for row in existing_pin_codes_query)

    # Iterate through the data and insert the entire JSON row if the pin code doesn't exist in the set
    new_pin_codes = []
    for row in data:
        pincode_str = str(row['pincode'])
        if pincode_str not in existing_pin_codes:
            new_pin_codes.append(row)

    # Bulk insert new pin codes
    if new_pin_codes:
        op.bulk_insert(PostalCodeMaster.__table__, new_pin_codes)

    # ### end Alembic commands ###
