"""create_performance_zone_table

Revision ID: 0030
Revises: 0029
Create Date: 2023-09-14 16:24:28.948541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0030'
down_revision = '0029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('az_performance_zone',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('asp_id', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('metrics_date', sa.Date(), nullable=True),
    sa.Column('asin', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_image', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('total_sales', sa.Numeric(), nullable=True),
    sa.Column('total_units_sold', sa.Integer(), nullable=True),
    sa.Column('sales_from_ads', sa.Numeric(), nullable=True),
    sa.Column('organic_sales', sa.Numeric(), nullable=True),
    sa.Column('percentage_organic_sales', sa.Numeric(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('clicks_from_ads', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Numeric(), nullable=True),
    sa.Column('cpc', sa.Numeric(), nullable=True),
    sa.Column('spend', sa.Numeric(), nullable=True),
    sa.Column('roas', sa.Numeric(), nullable=True),
    sa.Column('acos', sa.Numeric(), nullable=True),
    sa.Column('tacos', sa.Numeric(), nullable=True),
    sa.Column('ad_conversion_rate', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('az_performance_zone')
    # ### end Alembic commands ###
