"""update subscription table

Revision ID: 0036
Revises: 0035
Create Date: 2023-09-18 18:43:08.149011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0036'
down_revision = '0035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('subscription', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('subscription', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
