"""Update Category Brand in all table

Revision ID: 0039
Revises: 0038
Create Date: 2023-09-22 11:39:28.948273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0039'
down_revision = '0038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_fba_customer_shipment_sales', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_fba_customer_shipment_sales', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_fba_reimbursements', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_fba_reimbursements', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_fba_replacement', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_fba_replacement', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_fba_returns', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_fba_returns', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_financial_event', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_financial_event', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_ledger_summary', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_ledger_summary', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_order', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_order', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_order_item', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_order_item', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_order_report', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_order_report', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_product_performance', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_product_performance', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_return', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_return', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_sales_traffic_asin', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_sales_traffic_summary', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_settlement', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_settlement', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_settlement_v2', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_settlement_v2', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_sponsored_brand', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_sponsored_brand', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_sponsored_display', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_sponsored_display', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_sponsored_product', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_sponsored_product', sa.Column('brand', sa.String(length=250), nullable=True))
    op.add_column('az_stock_transfer_adhoc', sa.Column('category', sa.String(length=250), nullable=True))
    op.add_column('az_stock_transfer_adhoc', sa.Column('brand', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('az_stock_transfer_adhoc', 'brand')
    op.drop_column('az_stock_transfer_adhoc', 'category')
    op.drop_column('az_sponsored_product', 'brand')
    op.drop_column('az_sponsored_product', 'category')
    op.drop_column('az_sponsored_display', 'brand')
    op.drop_column('az_sponsored_display', 'category')
    op.drop_column('az_sponsored_brand', 'brand')
    op.drop_column('az_sponsored_brand', 'category')
    op.drop_column('az_settlement_v2', 'brand')
    op.drop_column('az_settlement_v2', 'category')
    op.drop_column('az_settlement', 'brand')
    op.drop_column('az_settlement', 'category')
    op.drop_column('az_sales_traffic_summary', 'brand')
    op.drop_column('az_sales_traffic_summary', 'category')
    op.drop_column('az_sales_traffic_asin', 'brand')
    op.drop_column('az_sales_traffic_asin', 'category')
    op.drop_column('az_return', 'brand')
    op.drop_column('az_return', 'category')
    op.drop_column('az_product_performance', 'brand')
    op.drop_column('az_product_performance', 'category')
    op.drop_column('az_order_report', 'brand')
    op.drop_column('az_order_report', 'category')
    op.drop_column('az_order_item', 'brand')
    op.drop_column('az_order_item', 'category')
    op.drop_column('az_order', 'brand')
    op.drop_column('az_order', 'category')
    op.drop_column('az_ledger_summary', 'brand')
    op.drop_column('az_ledger_summary', 'category')
    op.drop_column('az_financial_event', 'brand')
    op.drop_column('az_financial_event', 'category')
    op.drop_column('az_fba_returns', 'brand')
    op.drop_column('az_fba_returns', 'category')
    op.drop_column('az_fba_replacement', 'brand')
    op.drop_column('az_fba_replacement', 'category')
    op.drop_column('az_fba_reimbursements', 'brand')
    op.drop_column('az_fba_reimbursements', 'category')
    op.drop_column('az_fba_customer_shipment_sales', 'category')
    op.drop_column('az_fba_customer_shipment_sales', 'brand')
    # ### end Alembic commands ###
