"""update queuetask

Revision ID: 0044
Revises: 0043
Create Date: 2023-09-29 13:16:34.328328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0044'
down_revision = '0043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue_task', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('queue_task', 'account_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue_task', 'account_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('queue_task', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
