"""Updated Account table

Revision ID: 0045
Revises: 0044
Create Date: 2023-10-03 16:12:16.356319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0045'
down_revision = '0044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('asp_id_connected_at', sa.BigInteger(), nullable=True))
    op.add_column('account', sa.Column('asp_sync_started_at', sa.BigInteger(), nullable=True))
    op.add_column('account', sa.Column('asp_sync_completed_at', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'asp_sync_completed_at')
    op.drop_column('account', 'asp_sync_started_at')
    op.drop_column('account', 'asp_id_connected_at')
    # ### end Alembic commands ###
