"""Update Account table

Revision ID: 0047
Revises: 0046
Create Date: 2023-10-09 11:17:55.373090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0047'
down_revision = '0046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('asp_marketplace', sa.String(length=100), nullable=True))
    op.add_column('account', sa.Column('asp_marketplace_id', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'asp_marketplace_id')
    op.drop_column('account', 'asp_marketplace')
    # ### end Alembic commands ###
