"""add indexing

Revision ID: 0050
Revises: 0049
Create Date: 2023-10-10 18:22:03.235352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0050'
down_revision = '0049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_uuid_key', 'account', type_='unique')
    op.create_index(op.f('ix_account_uuid'), 'account', ['uuid'], unique=True)
    op.create_index(op.f('ix_subscription_account_id'), 'subscription', ['account_id'], unique=False)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index('ix_user_id_account_id', 'user_account', ['user_id', 'account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_id_account_id', table_name='user_account')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_index(op.f('ix_subscription_account_id'), table_name='subscription')
    op.drop_index(op.f('ix_account_uuid'), table_name='account')
    op.create_unique_constraint('account_uuid_key', 'account', ['uuid'])
    # ### end Alembic commands ###
