"""update user_invite table

Revision ID: 0051
Revises: 0050
Create Date: 2023-10-13 11:55:03.429887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0051'
down_revision = '0050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_invite_email_key', 'user_invite', type_='unique')
    op.create_unique_constraint('uq_invited_by_account_id_email', 'user_invite', ['invited_by_account_id', 'email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invited_by_account_id_email', 'user_invite', type_='unique')
    op.create_unique_constraint('user_invite_email_key', 'user_invite', ['email'])
    # ### end Alembic commands ###
