"""update performance_zone table

Revision ID: 0052
Revises: 0051
Create Date: 2023-10-16 13:42:08.555878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0052'
down_revision = '0051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_performance_zone', sa.Column('sku', sa.String(length=50), nullable=True))
    op.add_column('az_performance_zone', sa.Column('sub_category', sa.String(length=255), nullable=True))
    op.add_column('az_performance_zone', sa.Column('category_rank', sa.BigInteger(), nullable=True))
    op.add_column('az_performance_zone', sa.Column('subcategory_rank', sa.BigInteger(), nullable=True))
    op.add_column('az_performance_zone', sa.Column('order_from_ads', sa.BigInteger(), nullable=True))
    op.add_column('az_performance_zone', sa.Column('organic_units', sa.BigInteger(), nullable=True))
    op.add_column('az_performance_zone', sa.Column('organic_sessions', sa.BigInteger(), nullable=True))
    op.add_column('az_performance_zone', sa.Column('impressions', sa.BigInteger(), nullable=True))
    op.alter_column('az_performance_zone', 'asin',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('az_performance_zone', 'asin',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('az_performance_zone', 'impressions')
    op.drop_column('az_performance_zone', 'organic_sessions')
    op.drop_column('az_performance_zone', 'organic_units')
    op.drop_column('az_performance_zone', 'order_from_ads')
    op.drop_column('az_performance_zone', 'subcategory_rank')
    op.drop_column('az_performance_zone', 'category_rank')
    op.drop_column('az_performance_zone', 'sub_category')
    op.drop_column('az_performance_zone', 'sku')
    # ### end Alembic commands ###
