"""Updated Account table, Amazon Ad's Table, Report Table

Revision ID: 0053
Revises: 0052
Create Date: 2023-10-17 15:19:11.927005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0053'
down_revision = '0052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('az_ads_profile_ids', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('account', 'az_ads_profile_id')
    op.add_column('az_report', sa.Column('az_ads_profile_id', sa.String(length=255), nullable=True))
    op.add_column('az_sponsored_brand', sa.Column('az_ads_profile_id', sa.String(length=255), nullable=True))
    op.add_column('az_sponsored_display', sa.Column('az_ads_profile_id', sa.String(length=255), nullable=True))
    op.add_column('az_sponsored_product', sa.Column('az_ads_profile_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('az_sponsored_product', 'az_ads_profile_id')
    op.drop_column('az_sponsored_display', 'az_ads_profile_id')
    op.drop_column('az_sponsored_brand', 'az_ads_profile_id')
    op.drop_column('az_report', 'az_ads_profile_id')
    op.add_column('account', sa.Column('az_ads_profile_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('account', 'az_ads_profile_ids')
    # ### end Alembic commands ###
