"""Update Performance zone table

Revision ID: 0054
Revises: 0053
Create Date: 2023-10-30 15:26:39.258183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0054'
down_revision = '0053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_performance_zone', sa.Column('total_ad_units_sold', sa.Integer(), nullable=True))
    op.add_column('az_performance_zone', sa.Column('conversion_rate', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('az_performance_zone', 'conversion_rate')
    op.drop_column('az_performance_zone', 'total_ad_units_sold')
    # ### end Alembic commands ###
