"""update sales_traffic_summary table

Revision ID: 0058
Revises: 0057
Create Date: 2023-11-17 18:16:26.845399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0058'
down_revision = '0057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_sales_traffic_summary', sa.Column('hourly_sales', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('az_sales_traffic_summary', 'hourly_sales')
    # ### end Alembic commands ###
