"""Add unique key constraint to item master table

Revision ID: 0059
Revises: 0058
Create Date: 2023-11-28 19:07:04.808021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0059'
down_revision = '0058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('az_item_master_seller_sku_key', 'az_item_master', type_='unique')
    op.create_index('ix_unique_combination', 'az_item_master', ['account_id', 'selling_partner_id', 'seller_sku'], unique=False)
    op.create_unique_constraint('uq_account_selling_partner_id_seller_sku', 'az_item_master', ['account_id', 'selling_partner_id', 'seller_sku'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_account_selling_partner_id_seller_sku', 'az_item_master', type_='unique')
    op.drop_index('ix_unique_combination', table_name='az_item_master')
    op.create_unique_constraint('az_item_master_seller_sku_key', 'az_item_master', ['seller_sku'])
    # ### end Alembic commands ###
