"""Update SalesTrafficAsin table

Revision ID: 0060
Revises: 0059
Create Date: 2023-11-24 17:38:53.017191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0060'
down_revision = '0059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_sales_traffic_asin', sa.Column('hourly_sales', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('az_sales_traffic_asin', 'hourly_sales')
    # ### end Alembic commands ###
