"""Add FBA inventory json column to az_item_master table

Revision ID: 0061
Revises: 0060
Create Date: 2023-12-20 08:54:11.656403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0061'
down_revision = '0060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('az_item_master', sa.Column('fba_inventory_json', sa.JSON(), nullable=True))
    op.alter_column('az_item_master', 'listing_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('az_item_master', 'product_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('az_item_master', 'max_retail_price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('az_item_master', 'max_retail_price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('az_item_master', 'product_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('az_item_master', 'listing_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('az_item_master', 'fba_inventory_json')
    # ### end Alembic commands ###
